FROM rust:1.83 as builder

WORKDIR /usr/src/app
COPY . .

RUN apt-get update && apt-get install -y protobuf-compiler
RUN cargo build --release

FROM gcr.io/distroless/cc-debian12

WORKDIR /usr/local/bin

COPY --from=builder /usr/src/app/target/release/sensor-suricata-service-rust .

CMD ["./sensor-suricata-service-rust"]
